### PR TITLE
Make version explicit

### LINKED ISSUE #30: Versioning
This project should have version information deployed and communicate different states of CiRA.

My proposal for versioning is as follows:

**cira application:**

- Semantic version on a Python package level. So that CiRA could be distributed as a Python package.
- `setup.py` or something similar could be used to declare the version.
- REST API should be able to show the version of the application, e.g.,  with an endpoint like `/api/health` or `/api/version`.
- git tags or GitHub releases are not necessary since the main way of distributing CiRA will be Docker images.

**cira application Docker image:**

- A new build of the application Docker container will have two tags attached to the image: `latest` and the semantic version of the application, e.g., `1.3.2`.
- The application images always use `FROM cira-dev:latest` when created.
- Older versions can be pulled using the semantic version, e.g., `cira:1.3.2`.

**cira-dev Docker image:**

- A new build of the dev container has always the `latest` tag without any further versioning information. Previous states can be pulled by using the git hash, e.g., `cira-dev@sha256:0276f14...`.
- In my opinion, additional versioning information for the dev container confuses more than it helps.

### PR DESCRIPTION
**Pull request by JulianFrattini**
This PR closes #30 by adding a standardized, explicit way of defining the version of the CiRA pipeline in a `setup.py` file. While [PEP 518](https://peps.python.org/pep-0518/) already supersedes the user of `setup.py` to build distributions, this initial approach at versioning will suffice for now.

The `requirements.txt` could be removed, but I left them in for now. I am however not opposed to fully removing it once the changes in the scope of this PR are deemed sufficient.

### CODE REVIEW

**Comment by JulianFrattini** [comment]
All instances of `pip install -r requirements.txt` will have to be replaced by `pip install -e .`

**Comment by JulianFrattini** [comment]
To me, these are two distinct versions: the version in `setup.py` is the version of the CiRA pipeline, and the version in `app.py` is the version of the API. Or is that too confusing?

**Comment by andreas-bauer** [comment]
IMHO, It is too confusing.

Also, the purpose of the semantic version is to understand whether a version jump results in potential incompatibility of provided APIs.

**Comment by andreas-bauer** [comment]
E.g., CiRA version `0.9.0` with API `1.0.0` based on dev image `1.2` 😉 ->  KISS

**Comment by JulianFrattini** [comment]
Good question, I believe you are right. I will revert the use of the keyword.

**Review by andreas-bauer — APPROVED** [review]

**Pull request merged**
